version: "3.5"

services:
  
  photo:
    container_name: photo_server
    build: './DownloadploadPhotoServer'
    ports:
      - "8181:8181"

  db:
    container_name: db_postgres_container
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  main:
    container_name: main_server
    build: './MainServer'
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  